#pragma once
#include "FillBottomSideCellCommand.h"
#include "FillLeftBottomConnorCellCommand.h"
#include "FillLeftSideCellCommand.h"
#include "FillLeftTopConnorCellCommand.h"
#include "FillRightBottomConnorCellCommand.h"
#include "FillRightSideCellCommand.h"
#include "FillRightTopConnorCellCommand.h"
#include "FillTopSideCellCommand.h"